import "./css/main.css";
// import "./js/test.js";
// import "./js/fahm.js";
// import "./js/test2.js";
// import "./js/testSec.js";
// import "./js/testtolbat1.js";
// import "./js/sidebar.js";
// import "./js/testsandali.js";
// import "./js/entekhabEsmFaza.js";
//import "./js/halleditor.js";
import "./js/halleditor4.js";
